apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"  # Git image to perform clone operation
      script: |
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: build-command
      type: string
      description: The build command to run (e.g., make, mvn, gradle)
      default: "make"  # Adjust this to your build tool
  workspaces:
    - name: source
      description: The workspace containing the cloned source code
  steps:
    - name: build
      image: "alpine:latest"  # Adjust this to an appropriate image for your build tool
      script: |
        cd $(workspaces.source.path)
        echo "Hello World"
