apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned
  steps:
    - name: build
      image: "ubuntu:22.04"
      script: |
        echo "Cloning repository $(params.repository-url) on branch $(params.revision)"
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)
        echo "Repository cloned"
        cd $(workspaces.output.path)
        echo "Current directory: $(pwd)"
        ls -la
      workspaces:
        - name: output
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
