apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpc-ch-pipeline-nfs-pv
  labels:
    name: vpc-ch-pipeline-nfs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: cd-nfsserver.vpc-ch-pipeline.local
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpc-ch-pipeline-nfs-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 500Gi    
