apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-clickhouse
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/harishisnow/ClickHouse-repo.git 
        - name: revision
          value: main

