apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-clickhouse-pipeline
spec:
  params:
    - name: repository-url
      default: https://github.com/harishisnow/ClickHouse-repo.git 
      type: string
    - name: revision
      default: "master"
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-task
      params:
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared-workspace 
          workspace: shared-workspace

    - name: build-code
      taskRef:
        name: build-task
      workspaces:
        - name: shared-workspace 
          workspace: shared-workspace
      params:
        - name: build-command
          value: "make"  # Adjust this to your build tool (e.g., mvn package)
      runAfter:  # Ensure build task runs after clone task
        - clone-repo
